# This script prints the contents of the binary files generated by the io1a_* writers
# Usage: ./printdata.sh <binary file>
# Example: ./printdata mydata_00000.bin
# Source: I cannot recall

nl="$(od -e $1 | wc -l)"
nl=$((nl-1))
od -e $1 | head -n $nl | awk '{printf "%f %f\n",  $2, $3}'
